countries = {
    "Algeria": "africa/algeria",
    "Angola": "africa/angola",
    "Benin": "africa/benin",
    "Botswana": "africa/botswana",
    "Burkina Faso": "africa/burkina-faso",
    "Burundi": "africa/burundi",
    # "Cameroon": "africa/cameroon",
    # "Cape Verde": "africa/cape-verde",
    # "Central African Republic": "africa/central-african-republic",
    # "Chad": "africa/chad",
    # "Comoros": "africa/comoros",
    # "Republic of the Congo": "africa/congo",
    # "Cote d'Ivoire": "africa/cote-divoire",
    # "Democratic Republic of Congo": "africa/democratic-republic-of-congo",
    # "Djibouti": "africa/djibouti",
    # "Egypt": "africa/egypt",
    # "Equatorial Guinea": "africa/equatorial-guinea",
    # "Eritrea": "africa/eritrea",
    # "Eswatini": "africa/eswatini",
    # "Ethiopia": "africa/ethiopia",
    # "Gabon": "africa/gabon",
    # "Gambia": "africa/gambia",
    # "Ghana": "africa/ghana",
    # "Guinea": "africa/guinea",
    # "Guinea-Bissau": "africa/guinea-bissau",
    # "Kenya": "africa/kenya",
    # "Lesotho": "africa/lesotho",
    # "Liberia": "africa/liberia",
    # "Libya": "africa/libya",
    # "Madagascar": "africa/madagascar",
    # "Malawi": "africa/malawi",
    # "Mali": "africa/mali",
    # "Mauritania": "africa/mauritania",
    # "Mauritius": "africa/mauritius",
    # "Mayotte": "africa/mayotte",
    # "Morocco": "africa/morocco",
    # "Mozambique": "africa/mozambique",
    # "Namibia": "africa/namibia",
    # "Niger": "africa/niger",
    # "Nigeria": "africa/nigeria",
    # "Réunion": "africa/réunion",
    # "Rwanda": "africa/rwanda",
    # "Saint Helena": "africa/saint-helena",
    # "São Tomé and Príncipe": "africa/são-tomé-and-príncipe",
    # "Senegal": "africa/senegal",
    # "Seychelles": "africa/seychelles",
    # "Sierra Leone": "africa/sierra-leone",
    # "Somalia": "africa/somalia",
    # "South Africa": "africa/south-africa",
    # "South Sudan": "africa/south-sudan",
    # "Sudan": "africa/sudan",
    # "Togo": "africa/togo",
    # "Tunisia": "africa/tunisia",
    # "Uganda": "africa/uganda",
    # "United Republic of Tanzania": "africa/united-republic-of-tanzania",
    # "Zambia": "africa/zambia",
    # "Zimbabwe": "africa/zimbabwe",
    # "Afghanistan": "asia-central/afghanistan",
    # "Kazakhstan": "asia-central/kazakhstan",
    # "Kyrgyzstan": "asia-central/kyrgyzstan",
    # "Pakistan": "asia-central/pakistan",
    # "Tajikistan": "asia-central/tajikistan",
    # "Turkmenistan": "asia-central/turkmenistan",
    # "Uzbekistan": "asia-central/uzbekistan",
    # "Bangladesh": "asia-east/bangladesh",
    # "Bhutan": "asia-east/bhutan",
    # "Borneo": "asia-east/borneo",
    # "Brunei Darussalam": "asia-east/brunei-darussalam",
    # "Cambodia": "asia-east/cambodia",
    # "China": "asia-east/china",
    # "Democratic People's Republic of Korea": "asia-east/democratic-peoples-republic-of-korea",
    # "Hong Kong": "asia-east/hong-kong",
    # "India": "asia-east/india",
    # "Indonesia": "asia-east/indonesia",
    # "Kalimantan": "asia-east/indonesia",
    # "Bali": "asia-east/indonesia",
    # "Java": "asia-east/indonesia",
    # "Sumatra": "asia-east/indonesia",
    # "West Papua": "asia-east/indonesia",
    # "Japan": "asia-east/japan",
    # "Laos": "asia-east/laos",
    # "Macao": "asia-east/macao",
    # "Malaysia": "asia-east/malaysia",
    # "Maldives": "asia-east/maldives",
    # "Mongolia": "asia-east/mongolia",
    # "Myanmar": "asia-east/myanmar",
    # "Nepal": "asia-east/nepal",
    # "Philippines": "asia-east/philippines",
    # "Republic of Korea": "asia-east/republic-of-korea",
    # "Singapore": "asia-east/singapore",
    # "Sri Lanka": "asia-east/sri-lanka",
    # "Taiwan": "asia-east/taiwan",
    # "Thailand": "asia-east/thailand",
    # "Timor-Leste": "asia-east/timor-leste",
    # "Vietnam": "asia-east/vietnam",
    # "American Samoa": "australasia-pacific/american-samoa",
    # "Australia": "australasia-pacific/australia",
    # "Christmas Island": "australasia-pacific/christmas-island",
    # "Cook Islands": "australasia-pacific/cook-islands",
    # "Federated States of Micronesia": "australasia-pacific/federated-states-of-micronesia",
    # "Fiji": "australasia-pacific/fiji",
    # "French Polynesia": "australasia-pacific/french-polynesiata",
    # "Tahiti": "australasia-pacific/french-polynesiata",
    # "Guam": "australasia-pacific/guam",
    # "Kiribati": "australasia-pacific/kiribati",
    # "Marshall Islands": "australasia-pacific/marshall-islands",
    # "Nauru": "australasia-pacific/nauru",
    # "New Caledonia": "australasia-pacific/new-caledonia",
    # "New Zealand": "australasia-pacific/new-zealand",
    # "Niue": "australasia-pacific/niue",
    # "Northern Mariana Islands": "australasia-pacific/northern-mariana-islands",
    # "Palau": "australasia-pacific/palau",
    # "Papua New Guinea": "australasia-pacific/papua-new-guinea",
    # "Pitcairn": "australasia-pacific/pitcairn",
    # "Samoa": "australasia-pacific/samoa",
    # "Solomon Islands": "australasia-pacific/solomon-islands",
    # "Tokelau": "australasia-pacific/tokelau",
    # "Tonga": "australasia-pacific/tonga",
    # "Tuvalu": "australasia-pacific/tuvalu",
    # "Ellice Islands": "australasia-pacific/tuvalu",
    # "Vanuatu": "australasia-pacific/vanuatu",
    # "Anguilla": "caribbean/anguilla",
    # "Antigua and Barbuda": "caribbean/antigua-and-barbuda",
    # "Aruba": "caribbean/aruba",
    # "Bahamas": "caribbean/bahamas",
    # "Barbados": "caribbean/barbados",
    # "Bonaire": "caribbean/bonaire",
    # "British Virgin Islands": "caribbean/british-virgin-islands",
    # "Cayman Islands": "caribbean/cayman-islands",
    # "Cuba": "caribbean/cuba",
    # "Curaçao": "caribbean/curaçao",
    # "Dominica": "caribbean/dominica",
    # "Dominican Republic": "caribbean/dominican-republic",
    # "Grenada": "caribbean/grenada",
    # "Guadeloupe": "caribbean/guadeloupe",
    # "Haiti": "caribbean/haiti",
    # "Jamaica": "caribbean/jamaica",
    # "Martinique": "caribbean/martinique",
    # "Montserrat": "caribbean/montserrat",
    # "Netherlands Antilles": "caribbean/netherlands-antilles",
    # "Puerto Rico": "caribbean/puerto-rico",
    # "Saba": "caribbean/saba",
    # "Saint Barthelemy": "caribbean/saint-barthelemy",
    # "Saint Kitts and Nevis": "caribbean/saint-kitts-and-nevis",
    # "Saint Lucia": "caribbean/saint-lucia",
    # "Saint Martin": "caribbean/saint-martin",
    # "Saint Vincent and the Grenadines": "caribbean/saint-vincent-and-the-grenadines",
    # "Sint Eustatius": "caribbean/sint-eustatius",
    # "Sint Maarten": "caribbean/sint-maarten",
    # "Trinidad and Tobago": "caribbean/trinidad-and-tobago",
    # "Turks and Caicos": "caribbean/turks-and-caicos",
    # "US Virgin Islands": "caribbean/us-virgin-islands",
    # "Virgin Islands": "caribbean/virgin-islands",
    # "Belize": "central-america/belize",
    # "Costa Rica": "central-america/costa-rica",
    # "El Salvador": "central-america/el-salvador",
    # "Guatemala": "central-america/guatemala",
    # "Honduras": "central-america/honduras",
    # "Nicaragua": "central-america/nicaragua",
    # "Panama": "central-america/panama",
    # "Albania": "europe-russia/albania",
    # "Andorra": "europe-russia/andorra",
    # "Armenia": "europe-russia/armenia",
    # "Austria": "europe-russia/austria",
    # "Azerbaijan": "europe-russia/azerbaijan",
    # "Belarus": "europe-russia/belarus",
    # "Belgium": "europe-russia/belgium",
    # "Bosnia Herzegovina": "europe-russia/bosnia-herzegovina",
    # "Bulgaria": "europe-russia/bulgaria",
    # "Croatia": "europe-russia/croatia",
    # "Cyprus": "europe-russia/cyprus",
    # "Czech Republic": "europe-russia/czech-republic",
    # "Denmark": "europe-russia/denmark",
    # "Estonia": "europe-russia/estonia",
    # "Faroe Islands": "europe-russia/faroe-islands",
    # "Finland": "europe-russia/finland",
    # "France": "europe-russia/france",
    # "Georgia": "europe-russia/georgia",
    # "Germany": "europe-russia/germany",
    # "Gibraltar": "europe-russia/gibraltar",
    # "Greece": "europe-russia/greece",
    # "Corfu": "europe-russia/greece",
    # "Crete": "europe-russia/greece",
    # "Rhodes": "europe-russia/greece",
    # "Hungary": "europe-russia/hungary",
    # "Iceland": "europe-russia/iceland",
    # "Republic of Ireland": "europe-russia/ireland",
    # "Italy": "europe-russia/italy",
    # "Sardinia": "europe-russia/italy",
    # "Sicily": "europe-russia/italy",
    # "Kosovo": "europe-russia/kosovo",
    # "Latvia": "europe-russia/latvia",
    # "Liechtenstein": "europe-russia/liechtenstein",
    # "Lithuania": "europe-russia/lithuania",
    # "Luxembourg": "europe-russia/luxembourg",
    # "Malta": "europe-russia/malta",
    # "Monaco": "europe-russia/monaco",
    # "Montenegro": "europe-russia/montenegro",
    # "Netherlands": "europe-russia/netherlands",
    # "Norway": "europe-russia/norway",
    # "Poland": "europe-russia/poland",
    # "Portugal": "europe-russia/portugal",
    # "Azores": "europe-russia/portugal",
    # "Madeira": "europe-russia/portugal",
    # "Republic of Moldova": "europe-russia/republic-of-moldova",
    # "Republic of North Macedonia": "europe-russia/republic-of-north-macedonia",
    # "Romania": "europe-russia/romania",
    # "Russian Federation": "europe-russia/russian-federation",
    # "San Marino": "europe-russia/san-marino",
    # "Serbia": "europe-russia/serbia",
    # "Slovakia": "europe-russia/slovakia",
    # "Slovenia": "europe-russia/slovenia",
    # "Spain": "europe-russia/spain",
    # "Majorca": "europe-russia/spain",
    # "Minorca": "europe-russia/spain",
    # "Balearic Islands": "europe-russia/spain",
    # "Ibiza": "europe-russia/spain",
    # "Formentera": "europe-russia/spain",
    # "Canary Islands": "europe-russia/spain",
    # "Gran Canaria": "europe-russia/spain",
    # "Tenerife": "europe-russia/spain",
    # "Lanzarote": "europe-russia/spain",
    # "Fuerteventura": "europe-russia/spain",
    # "Sweden": "europe-russia/sweden",
    # "Switzerland": "europe-russia/switzerland",
    # "Turkey": "europe-russia/turkey",
    # "Ukraine": "europe-russia/ukraine",
    # "England": "europe-russia/united-kingdom",
    # "Scotland": "europe-russia/united-kingdom",
    # "Wales": "europe-russia/united-kingdom",
    # "Northern Ireland": "europe-russia/united-kingdom",
    # "Channel Islands": "europe-russia/united-kingdom",
    # "Isle of Man": "europe-russia/united-kingdom",
    # "United Kingdom": "europe-russia/united-kingdom",
    # "Bahrain": "middle-east/bahrain",
    # "Iran": "middle-east/iran",
    # "Iraq": "middle-east/iraq",
    # "Israel and Occupied Palestinian Territories": "middle-east/israel-and-occupied-palestinian-territories",
    # "Jordan": "middle-east/jordan",
    # "Kuwait": "middle-east/kuwait",
    # "Lebanon": "middle-east/lebanon",
    # "Oman": "middle-east/oman",
    # "Qatar": "middle-east/qatar",
    # "Saudi Arabia": "middle-east/saudi-arabia",
    # "Syria": "middle-east/syria",
    # "United Arab Emirates": "middle-east/united-arab-emirates",
    # "Dubai": "middle-east/united-arab-emirates",
    # "Abu Dhabi": "middle-east/united-arab-emirates",
    # "Yemen": "middle-east/yemen",
    # "Bermuda": "north-america/bermuda",
    # "Canada": "north-america/canada",
    # "Greenland": "north-america/greenland",
    # "Mexico": "north-america/mexico",
    # "Saint Pierre and Miquelon": "north-america/saint-pierre-and-miquelon",
    # "United States of America": "north-america/united-states-of-america",
    # "Maui": "north-america/united-states-of-america",
    # "Oahu": "north-america/united-states-of-america",
    # "Hawaii": "north-america/united-states-of-america",
    # "Alaska": "north-america/united-states-of-america",
    # "Antarctica": "south-america-antarctica/antarctica",
    # "Argentina": "south-america-antarctica/argentina",
    # "Bolivia": "south-america-antarctica/bolivia",
    # "Brazil": "south-america-antarctica/brazil",
    # "Chile": "south-america-antarctica/chile",
    # "Colombia": "south-america-antarctica/colombia",
    # "Ecuador": "south-america-antarctica/ecuador",
    # "Falkland Islands": "south-america-antarctica/falkland-islands",
    # "French Guiana": "south-america-antarctica/french-guiana",
    # "Guyana": "south-america-antarctica/guyana",
    # "Paraguay": "south-america-antarctica/paraguay",
    # "Peru": "south-america-antarctica/peru",
    # "Suriname": "south-america-antarctica/suriname",
    # "Uruguay": "south-america-antarctica/uruguay",
    "Venezuela": "south-america-antarctica/venezuela"
}